# Generated by Django 4.1.2 on 2023-06-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskTile',
            new_name='taskTitle',
        ),
    ]
